if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
settings.inlinetex=true;
deletepreamble();
defaultfilename="complex-numbers-problems-181-190-4";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

import geometry;
import olympiad;
import fontsize;
unitsize(2cm);
defaultpen(fontsize(6pt));
pair a = (0,2);
pair b = (-1,0);
pair c = (0.5,0);
show(triangle(a, b, c), 0.5*green);
pair o = orthocentercenter(a,b,c);
dot(o);
draw(a -- intersectionpoint(perpendicular(a, line(b, c)), line(b, c)));
draw(b -- intersectionpoint(perpendicular(b, line(a, c)), line(a, c)));
draw(c -- intersectionpoint(perpendicular(c, line(a, b)), line(a, b)));
label("$H$", o, align=NE);
pair p = intersectionpoint(perpendicular(a, line(b, c)), line(b, c));
draw(rightanglemark(a, p, b, 1.5));
