if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
settings.inlinetex=true;
deletepreamble();
defaultfilename="complex-numbers-problems-181-190-2";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

import geometry;
import fontsize;
unitsize(2cm);
defaultpen(fontsize(6pt));
pair a = (0,2);
pair b = (-1,0);
pair c = (0.5,0);
show(triangle(a, b, c), 0.5*green);
path p = circumcircle(a, b, c);
draw(p, 0.5*green);
pair o = circumcenter(a,b,c);
dot(o, 0.5*blue);
draw(a -- intersectionpoint(line(a, o), line(b,c)));
label("$D$", intersectionpoint(line(a, o), line(b,c)), align=S, 0.5*green);
draw(b -- o);
draw(c -- o);
pair l = intersectionpoint(line(a, o), line(b,c));
draw(o -- intersectionpoint(perpendicular(o, line(b, c)), line(b, c)));
draw("$L$", intersectionpoint(perpendicular(o, line(b, c)), line(b, c))-(0,.1), align= S, 0.5*green);
markangle("$2B$", radius=5, c, o, a, 0.5*green);
markangle("$2C$", radius=5, a, o, b, 0.5*green);
markangle("$\pi - 2C$", radius=10, b, o, l, 0.5*red);
markangle("$\pi - 2B$", radius=10, l, o, c, 0.5*blue);
