if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
settings.inlinetex=true;
deletepreamble();
defaultfilename="complex-numbers-algebra-5";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

import geometry;
import fontsize;
unitsize(1cm);
draw((1,0) -- (2,2), dashed);
draw((-1,0) -- (2,2), dashed);
draw((2,2) -- (3,4), arrow=Arrow);
draw((2,2) -- (3.5,3), arrow=Arrow);
draw((-1.5,0) --(4, 0), arrow=Arrow);
draw((0,-.3) --(0, 2.5), arrow=Arrow);
label("$x$", (4,0), align=E);
label("$y$", (0,2.5), align=N);
label("$O$", (0,0), align=SW);
markangle("$\theta$", radius=10, (3.5,3), (2,2), (3,4));
markangle("$\alpha$", radius=10, (3,0), (1,0), (2,2));
markangle("$\beta$", radius=10, (3,0), (-1,0), (2,2));
label("$P(z_1)$", (2,2), align=E);
label("$Q(z_2)$", (3,4), align=NE);
label("$R(z_3)$", (3.5,3), align=NE);
