if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
settings.inlinetex=true;
deletepreamble();
defaultfilename="complex-numbers-problems-201-210-1";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

import geometry;
import fontsize;
unitsize(0.5cm);
defaultpen(fontsize(6pt));
pair o = (0,0);
path circle = circle(o, 2);
draw(circle);
pair a = (0, 2);
pair b = (1.414, -1.414);
pair c = (-1.414, -1.414);
draw (a -- b -- c -- cycle);
draw (b -- o);
draw (c -- o);
label("$A$", a, align=N);
label("$B$", b, align=E);
label("$C$", c, align=W);
label("$O$", o, align=N);
markangle("", radius=10, c, o, b);
