if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
settings.inlinetex=true;
deletepreamble();
defaultfilename="complex-numbers-part4-3";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

import geometry;
import fontsize;
unitsize(1cm);
defaultpen(fontsize(6pt));
defaultpen(linewidth(0.3));
draw((-1, 0) -- (1, 0));
draw((0, -0.2) -- (0, 2.2));
draw((-1, 0) -- (0, 2));
draw((1, 0) -- (0, 2));
label("$A(z_1)$", (-1, 0), align=SW);
label("$B(z_2)$", (1, 0), align=SE);
Label l = Label("|$z - z_1|$", (-.5,1));
l = rotate(atan(2)*180/pi)*l;
label(l, (-.5, 1), align=W);
Label l = Label("|$z - z_2|$", (.5,1));
l = rotate(atan(-2)*180/pi)*l;
label(l, (.5, 1), align=E);
label("$z$", (0,2), align=E);
