if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
settings.inlinetex=true;
deletepreamble();
defaultfilename="complex-numbers-part3-6";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

import geometry;
import fontsize;
unitsize(1cm);
defaultpen(fontsize(6pt));
defaultpen(linewidth(0.3));
pair a = (0, 3);
pair b = (-2, 0);
pair c = (2, 0);
triangle t = triangle(a, b, c);
pair p = incenter(t);
line l1 = line(a, p);
line l2 = line(b, p);
line l3 = line(c, p);
pair d = intersectionpoint(l1, line(b, c));
draw(a -- d);
pair e = intersectionpoint(l2, line(a, c));
draw(b -- e);
pair f = intersectionpoint(l3, line(a, b));
draw(c -- f);
show(t, LA="", LB="", LC="", La="", Lb="", Lc="");
label("$A(z_1)$", a, align=N);
label("$B(z_1)$", b, align=SW);
label("$C(z_3)$", c, align=SE);
label("$D$", d, align=S);
label("$E$", e, align=E);
label("$F$", f, align=W);
label("$I(z)$", p + (0, 0.2), align=NE);
