if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
settings.inlinetex=true;
deletepreamble();
defaultfilename="complex-numbers-problems-201-210-2";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

import geometry;
import fontsize;
unitsize(0.5cm);
defaultpen(fontsize(6pt));
pair o1 = (2, 0);
path circle = circle(o1, 2);
draw(circle);
pair o = (0, 0);
pair p = (4, 0);
pair q = (3, 1.732);
pair r = (1, 1.732);
draw (o -- p);
draw (o -- q);
draw (o -- r);
draw (p -- q);
draw (p -- r);
markangle("$\theta$", radius=8, p, o, q);
markangle("$\theta$", radius=10, q, o, r);
markangle("$90^\circ$", radius=5, o, q, p);
markangle("$90^\circ$", radius=5, o, r, p);
label("$O$", o, align=W);
label("$P(z_1)$", p, align=E);
label("$Q(z_2)$", q, align=N);
label("$R(z_3)$", r, align=N);
